services:
  solr:
    container_name: meic_solr

    image: solr:9.7

    ports:
     - "8983:8983"

    volumes:
      - solr_data:/data

    command:
      - solr-precreate
      - songs

volumes:
  solr_data:
    driver: local
    driver_opts:
      type: none
      device: data
      o: bind